name: "Mailrise"
description: "An SMTP gateway for Apprise notifications."
version: "latest"
slug: "mailrise"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/YoRyan/mailrise"
ports:
  8025/tcp: 8025
map:
  - type: data
    read_only: false
image: ghcr.io/yoryan/mailrise
options:
  mailrise_config: ""
schema:
  mailrise_config: multiline