name: "Mailrise"
description: "An SMTP gateway for Apprise notifications."
version: "latest"
slug: "mailrise"
init: false
arch:
  - aarch64
  - amd64
url: "https://github.com/YoRyan/mailrise"
ports:
  8025/tcp: 8025
map:
  - type: homeassistant_config
    read_only: True
image: ghcr.io/yoryan/mailrise